add: Company page relationship
s1f102100793/spica pull request #39
Opened 2023-11-29 17:45 UTC by s1f102100793

## 行ったこと
1.Employeeのマイページから会社での役割が
「正社員」= 「company.roleId === 1」の時と「アルバイトだけど権限は正社員」= 「company.roleId === 2」の時に
会社ページに遷移できるボタンの表示するようにした。

2.companyIdをuuidにしたことによる、型の変更。フォルダ名を[companyId]に変更することでDynamic Routesに変更。

3.RightMembersSection.tsxのuseEffectで無限ループを修正、その結果[companyId]/membersページで2回レンダリングが
行われるようになった。この修正により、[companyId]配下のURL3つで移動する際にrouter.pushで移動できるようになり
navigateTo関数をuseRouteCompanyId.tsxに作成。

### 1の変更画像

<img width="960" alt="image" src="https://github.com/s1f102100793/spica/assets/85666759/949bf3d0-5753-41e4-b094-cb18a6240e46">

マック赤羽店ページへの部分

2023-11-30 07:12 UTC, chanon-mike requested changes
全体的にいいと思います。
Roleの実装はちょっとかも。

2023-11-30 12:41 UTC, s1f102100793 commented on client/src/components/CompanySection/RightMembersSection/RightMembersSection.tsx
この部分は今後、データベースからもってきた情報の値に変更するから、その時に型を作るかも

2023-11-30 12:50 UTC, s1f102100793 commented on client/src/components/CompanySection/RightMembersSection/RightMembersSection.tsx
> +  const [sortedMembers, setSortedMembers] = useState<Member[]>([]);
前の書き方だと再レンダリングがこのuseEffectでずっと起きていて、それを防ぐためってのと、
表示するようの状態を保存するためかな。

2023-11-30 12:50 UTC, s1f102100793 commented on client/src/components/CompanySection/RightMembersSection/RightMembersSection.tsx
確かに
データベースから実際に情報をもってきてから変更するかも

2023-11-30 13:22 UTC, s1f102100793 commented
1.divタグからbuttonタグへの変更

2.RightMembersSectionにおけるuseMemoの使用とその他少しの変更を行いました。

roleIdを用いたページ移動用のaタグの表示の部分はまだベストな案が思いつかないから、まだ解決できないかも

2023-11-30 15:47 UTC, s1f102100793 commented on client/src/components/MyPageSection/LeftSection.tsx/LeftSection.tsx
> +          .filter((company) => company.roleId === 1 || company.roleId === 2)
確かにこっちの方がコードとして分かりやすいし、読み手にも伝わりやすいからこうしよう。
ありがと

2023-11-30 15:54 UTC, s1f102100793 commented on client/src/components/MyPageSection/LeftSection.tsx/LeftSection.tsx
> +          .filter((company) => company.roleId === 1 || company.roleId === 2)
変更した。
データベースのロールがこれから追加されたり変更があったらこの部分変更する。

とりあえず現状維持。

2023-12-01 10:14 UTC, chanon-mike approved these changes

2023-12-02 07:48 UTC, merged