Creation of getStaticPaths. Accompanying complex changes
s1f102100793/spica pull request #42
Opened 2023-12-02 16:18 UTC by s1f102100793

## 行ったこと
1.tip関連のコードのCompanyIdとUserIdの使用。そしてキャメルケースへの変更。

2.tip/[company_id]/[user_id]からtip/[companyId]/[userId]へのキャメルケースの変更。
　server/repository/companyRepository.tsにallCompanyIdsとpostCompanyInfoの作成。
　api周りとgetStaticPathsの部分は一番最後のコミットで修正してあります。
　
3.LeftSection.tsxというフォルダ名っだったことに気づいたので修正。

4.apiの設計を変更しました。
　単数形を複数形に変更。
　api配下のフォルダで重要な部分をcompaniesとemployeesとtipフォルダにしました。
　それによっていらない部分の見直しをしました。

5.tip/[companyId]ページのgetStaticPathsなどでapiをたたくときにqueryを使うように変更しました。
　とりあえず使い方が何となくでしかわからなかったから、getするときにqueryを使うみたいな認識で作りました。
　queryのあるなしで呼び出す関数を分ければ1つのgetで対応できると思ってこの形にしました。
　この使い方が正しかったら、tip/[companyId]/[userId]ページでも同じようなことをしてカスタムフックでまとめようかと思ってます。

### 背景
まずチップページの情報をデータベースにつなげようとして、useEffectでページがレンダリングされるたびに
DBからデータを持ってくるか、buildするときにページを作るかを考え、buildするときに作る方がスピードが速いと知り、
getStaticPathsとgetStaticPropsを使ってページを作ることにした。

その際にapiフォルダの構造がぐちゃぐちゃで複雑になったため、apiの構造を再設計しました。
その後再設計されたapiを使用したgetStaticPropsなどに変更しました。

１つのPRにめちゃくちゃいろんなものが含まれていてすみません🙇‍♂️
今度クリスマスが近いんでケンタッキーおごります。

2023-12-02 17:08 UTC, s1f102100793 commented
CORSの許可しているURLが
https://spica-develop.vercel.app/ だけだからvercelのデプロイをするときにgetStaticPathsの部分でバックエンドのapiを
たたくから、そもそもエラーが起きてデプロイが失敗している。
コミットを追加したけどURLの形をみたらvercelのURLの形気持ち悪いから、そのコミットも意味がなかった
CORSのURLをリストで受け取れる設定に変えるかも

2023-12-04 14:00 UTC, chanon-mike requested changes

2023-12-04 14:00 UTC, chanon-mike commented on server/api/employees/1/index.ts
これは`employees/1`になっているけど、なぜ？

2023-12-04 14:00 UTC, chanon-mike commented on server/api/companies/controller.ts
> +}));
今のパスは`api/companies?companyId=<companyId>`になっているね。
このURIパスを見るだけだと、
- companyIdがない→全てのcompanyを返す
- companyIdがある→特定のcompanyを返す

しかし、今はidがあったらidだけを返すけど、nameは返さない。
もし、こういう感じでしたければ、
- `api/companies?fields=*`：全てのcompanyで全てのフィルドを返す
- `api/companiesI?fields=companyId`：全てのcompanyでcompanyIdだけを返す
- `api/companies/<companyId>?fields=*`：特定のcompanyで全てを返す
- `api/companies/<companyId>?fields=companyId`：特定のcompanyでcompanyIdを返す
の方がいい気がする

2023-12-04 14:00 UTC, chanon-mike commented on client/src/pages/tip/[companyId]/index.page.tsx
> +  };
ここはエラーハンドラーが必要？

2023-12-04 16:09 UTC, s1f102100793 commented
これはemployees/1になっているけど、なぜ？

この部分だけ解消した

2023-12-05 02:20 UTC, chanon-mike commented on client/src/pages/tip/[companyId]/index.page.tsx
> +  };
必要ないというのはここがエラーになっても問題ない？
https://github.com/s1f102100793/spica/blob/80c9375ef3c093b86ca71c72e1b137e9d44463e3/server/useCase/paypayUseCase.ts#L59-L87

2023-12-05 02:33 UTC, chanon-mike commented on server/api/companies/controller.ts
> +}));
OpenAPIじゃないから、APIはどうでもいいかもしれない。今後は使わないだろうと考えたから、どうやってもいいだろう。
行いたかったことはわかるけど、そもそもエンドポイントの設計がちょっと違うかも。
というのは二つの問題が現れる。

1. API設計が統一されていない

- `/employees/<employeesId>`：特定のemployeeの全てを返す
- `/companies?companyId=<id>`：特定のcompanyの全てを返す
- `/companies`：全てのcompanyのIDを返す
- 特定のリソースを取得するときにどっちかを一つ選んで統一しましょう（クエリーパラメターを使うか？パスパラメターを使うか？）
- 正直今コメント書いた途中でもよくわからない。コードを何回読まないといけなかったし、どういう意味なの？と思う

あとは問題はこれ
> companyIdがない→全てのcompanyのIDを返す
> companyIdがある→特定のcompanyの全てを返す
読んでも変と思わない？

2. 将来が開発して、機能が増える、他のフィルドも取得したいとなったらどうやるの？また、他の人がコードを読んだら疑問は絶対ある。それいいコードがどうか？

2023-12-05 06:42 UTC, s1f102100793 commented on server/api/companies/controller.ts
> +}));
「API設計が統一されていない」について
確かに過ぎます。

>companyIdがない→全てのcompanyのIDを返す
>companyIdがある→特定のcompanyの全てを返す
の部分に関しては気持ち悪いなとは思っていたけど、この場合すべてのcompanyのすべてを返すなどに対応させる必要があるのか、分からなくてどうすれば良いか分からなかった。

API設計が統一されていない問題に関しては
特定の会社、従業員の情報のすべてを返すときにパスパラメーターを使い、その中で限られた情報が欲しいときに
クエリパラメータを使おうと思う。

特定のemployeeの全てを返す、特定のcompanyの全てを返すは/employees/<employeesId>このような形式
特定のemployeeの特定の名前だけ返す時は/employees/<employeesId>?nameみたいな感じ（一例としてね）
全てのcompanyのIDを返す部分は/companiesつまりすべての会社の情報を持ってくる中の/companies?idみたいな
感じにしようと思う。

クエリパラメータに関してはまだよく詳しくは分かっていないからもう少し調べてみる。

2023-12-05 06:48 UTC, s1f102100793 commented on client/src/pages/tip/[companyId]/index.page.tsx
> +  };
この部分でさPromise<string>でURLだけ帰ってくるからエラーハンドラー必要無いと思っちゃった。

2023-12-06 04:57 UTC, s1f102100793 commented
## 変更内容
1.companiesのAPI設計を1からやり直した。パスパラメータで特定の会社の情報を取得することができ、クエリパラメータで取得する情報に制限を掛けるようにした。
この変更によるcompanyrepository.ts内の関数の変更、Promiseで使う型の作成をmodels.tsで行った。tip/[companyId]/index.page.tsxではAPIの呼び出しの変更、resbodyの変更による修正を加えた。

### 疑問点
1.バックエンドの関数のPromiseにPartialを使う事で各要素に「 | undefined」の意味を持たせてPartial<CompanyModel[]>にしているがtoCompanyModelのような関数で型を定義させた方が良いか。

2.PartialによってCompanyTipPagePropsの型にも「 | undefined」を加えることになってしまっていて、現状では動いてるが型がなんとなく気持ち悪い。

3.api/companies/_companyId@string/と設定しているが_companyId@CompanyIdの方が良いのか。_companyId@CompanyIdにするとnpm run notiosの時にエラーは起きるが、動く。エラーを起こしたくなかったので今の形にした。

2023-12-06 10:19 UTC, chanon-mike requested changes

2023-12-06 10:19 UTC, chanon-mike commented on server/repository/companyRepository.ts
> +  }
早期リターンを使ってelse文をなくす

2023-12-06 15:14 UTC, s1f102100793 commented on server/api/companies/_companyId@string/controller.ts
> +    const companyId = params.companyId as CompanyId;
型を変換するメソッドなんてある？

2023-12-06 15:18 UTC, s1f102100793 commented on server/repository/companyRepository.ts
> +  return prismaAllCompanyInfo as unknown as Partial<CompanyModel[]>;
思ってました。

2023-12-07 15:18 UTC, chanon-mike commented
Githubワークフローをもう一回ランして、テストが通るかどうかも要確認

2023-12-08 15:23 UTC, s1f102100793 commented on server/repository/companyRepository.ts
> +  }
確かに
変更する。

2023-12-08 15:32 UTC, s1f102100793 commented on server/repository/employeeRepository.ts
> +      createdAt: tip.createdAt,
model.tsでcreatedAt: z.date(),に統一をしたんだよね

z.number()で後に.getTime()を使うより良いかなって考えた

2023-12-08 15:46 UTC, s1f102100793 commented
Testが通らないのはひろきも同じエラーになってるから、松田さんがなんかFirebaseのいじったのかなーとか思っている。

2023-12-09 08:05 UTC, chanon-mike commented on server/repository/employeeRepository.ts
> +      createdAt: tip.createdAt,
そうだね。おそらくJSのDate型がややこしいから、numberの型でやって、DateTimeとかに変換した方が楽？
あくまで推測、詳しい理由はわからない。多分増田さんに聞いた方が詳しい。

https://github.com/solufa/next-frourio-starter/blob/87955a39c8c53ec73ded5666bc7bb3cd136428cd/server/repository/tasksRepository.ts#L9-L14

2023-12-09 16:57 UTC, s1f102100793 commented
## 行ったこと
createdAtの型変更、それによる様々な部分の微修正

2023-12-10 15:27 UTC, chanon-mike approved these changes
ナイス

2023-12-11 00:13 UTC, merged