fix: Spica home page
s1f102100793/spica pull request #43
Opened 2023-12-04 14:11 UTC by s1f102100793

## 背景
Spicaの方向性が以前は飲食店アルバイトのGitHubだったが、今はチップサービスに変わったので
ホームページを変える必要があった。

## 行ったこと
Spicaのホームページ変更
画像の部分に関しては今後作成します。

before
<img width="960" alt="スクリーンショット 2023-12-04 230551" src="https://github.com/s1f102100793/spica/assets/85666759/03e79d2f-5ecd-44c9-a3d0-b8617d02c358">
<img width="959" alt="スクリーンショット 2023-12-04 230607" src="https://github.com/s1f102100793/spica/assets/85666759/5de240b9-1ce3-4546-b442-1e5586a14680">
<img width="960" alt="スクリーンショット 2023-12-04 230616" src="https://github.com/s1f102100793/spica/assets/85666759/dfc84ec5-7fdd-4818-aa47-1ecb35fc76f1">

after
<img width="960" alt="image" src="https://github.com/s1f102100793/spica/assets/85666759/abe3695d-1274-4421-a781-b754f795574b">
<img width="959" alt="スクリーンショット 2023-12-04 230757" src="https://github.com/s1f102100793/spica/assets/85666759/972c34a6-1f09-49fc-95f5-fe03f34f47d1">
<img width="959" alt="スクリーンショット 2023-12-04 230816" src="https://github.com/s1f102100793/spica/assets/85666759/1adb7df5-4b6c-4048-af51-d59080ada00b">

2023-12-04 14:30 UTC, chanon-mike reviewed
Heroでちょっと画像との違和感は感じない？
Meritsのバッジではボーダーはいらない気がする。

2023-12-04 14:30 UTC, chanon-mike commented on client/src/components/Home/Merit/Merit.tsx
> +  }, []);
cssで書いた方がいいのでは？

2023-12-07 10:16 UTC, s1f102100793 commented on client/src/components/Home/Merit/Merit.tsx
> +  }, []);
<img width="501" alt="image" src="https://github.com/s1f102100793/spica/assets/85666759/593dca70-89d6-488f-8f68-16020f796c4b">

この部分で
文字と画像の順番を交互にしているんだけど
それをスマホサイズとかにするときに、cssで順番変えられなく無い？

2023-12-07 10:25 UTC, s1f102100793 commented
Heroでちょっと画像との違和感は感じない？
→そうなんかな、よく分からない笑

Meritsのバッジではボーダーはいらない気がする。
バッジが分からないな。

https://business.timee.co.jp/?utm_term=%E3%82%BF%E3%82%A4%E3%83%9F%E3%83%BC&utm_campaign=client_search_brand_g&utm_source=adwords&utm_medium=ppc&hsa_acc=6839075880&hsa_cam=20273377813&hsa_grp=150929865835&hsa_ad=662027345429&hsa_src=g&hsa_tgt=kwd-363553438691&hsa_kw=%E3%82%BF%E3%82%A4%E3%83%9F%E3%83%BC&hsa_mt=e&hsa_net=adwords&hsa_ver=3&gad_source=1&gclid=CjwKCAiA98WrBhAYEiwA2WvhOg9Bq5xtWxoDD_PucLkhmvQ_sENYzpWu0bBJ9r3fNdtjW4YXmtTq2BoC2xIQAvD_BwE

このタイミーのホームページを参考に作った。

2023-12-07 15:20 UTC, chanon-mike approved these changes

2023-12-07 15:24 UTC, chanon-mike requested changes
> この部分で
文字と画像の順番を交互にしているんだけど
それをスマホサイズとかにするときに、cssで順番変えられなく無い？

変えられる部分もあると思う、[Bootstrapの例](https://getbootstrap.com/docs/4.0/layout/grid/)でこう言う感じのGridで変えられる。
完全にレイアウトを変えたい時には難しい時もあるから、それは別のコンポーネントを作るべき。
`Desktopxxxx`や`Mobilexxxx`とかでコンポーネント分ける。状態で管理しない。

2023-12-09 07:57 UTC, chanon-mike approved these changes
なるほど。
生なCSSでorderかけるんだー

2023-12-09 16:37 UTC, merged