add: createTipData
s1f102100793/spica pull request #46
Opened 2023-12-14 14:20 UTC by s1f102100793

## 行ったこと
1.型などの詳細変更

2.実際にPayPayのwebフックを受取る部分の設定

3.redisの作成とgenerateQRCodeの引数の変更

4.PayPayの情報をredisを使って一時保存をし、その情報をkeyを使って取得し、データベースに保存するようにした。

## 背景
PayPayのwebフックを追加しようとしたが、feedbackなどの情報をフックに含めることができないため
キャッシュに一時的に情報を保持してもらうためにredisを使用した。
Dockerでできそうだったのでドッカーで行い、本番環境はenvの中身を変えるようにした

2023-12-14 15:08 UTC, chanon-mike requested changes
ファイルの数や変更が多いから見落としたかもしれないが、大きく見たのはフロントとバックの型。そして、redisのレポ層の実装

2023-12-14 15:08 UTC, chanon-mike commented on server/repository/redisRepository.ts
> +};
ここはRedisRepositoryなのにPaypayDataやTipDataの型を使っている。
`getKey`や`setKey`などで汎用なレポを作るべき。
Paypayなどはビジネスのユースケースだから、ユースケース層でそういう型を使うといいと思う。

2023-12-14 15:08 UTC, chanon-mike commented
あと、lint通らないっぽい

2023-12-15 04:17 UTC, s1f102100793 commented
## 行ったこと
1.型の修正

2.redisRepositoryの汎用化。関数に入る前にJSON.stringifyでstringにするようにした・

3.tipRepositoryも形をredisRepositoryに形を合わせて変更した。

2023-12-16 11:58 UTC, chanon-mike approved these changes
`as string`でちょっとあれなんだけで、まあ大丈夫かな？

2023-12-17 04:20 UTC, merged